name: Setup Cloudflare Warp
  # You may pin to the exact commit or the version.
  # uses: Boostport/setup-cloudflare-warp@1304cd04a70008c9a7a2f72540a53c13fc09f0d2
  uses: Boostport/setup-cloudflare-warp@v1.6.0
  with:
    # The version of Cloudflare Warp to install
    version: # optional
    # The name of your Zero Trust organization
    organization: tsaba
    
    
